default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: rails_project_dev

test:
  <<: *default
  database: rails_project_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default
  database: rails_project_test

production:
  <<: *default
  database: rails_project_prod
